// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreTest.Models.second_dbfirstTry;

[Index("BookId", Name = "IX_BookPrices_BookId")]
[Index("CurrencyId", Name = "IX_BookPrices_CurrencyId")]
public partial class BookPrice
{
    [Key]
    public int Id { get; set; }

    public int BookId { get; set; }

    public int CurrencyId { get; set; }

    public int Amount { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookPrices")]
    public virtual Book Book { get; set; } = null!;

    [ForeignKey("CurrencyId")]
    [InverseProperty("BookPrices")]
    public virtual Currency Currency { get; set; } = null!;
}